<?php
define('MYSQL_HOSTNAME','localhost');
define('MYSQL_DBNAME','a8730870ma');
define('MYSQL_USERNAME','a8730870ma');
define('MYSQL_PASSWORD','TcXdvEJHy');
define('MYSQL_CHARSET','utf8');
define('SALT','USHv87h08jkdnlv2dhso*(w32rds');
define('SUPERLOGIN','login');
define('SUPERPASSWORDHASH','$2y$10$U/tiG5ghu.NRRgMiU5yg8.MsLvKALe5wCwf7BbbT/ffm8B4hqDzyG');
define('SUPERPASSWORD','1DR2lc7h');
define('APPLICATION','6607104');